<a href="https://colab.research.google.com/github/Ainy07/PyTorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install torch torchvision torchaudio

In [12]:
import torch

a = torch.tensor(5)
b = torch.tensor(7)

c = a + b

print("Output:", c)

Output: tensor(12)


In [13]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = x+y
print(z)

tensor([5, 7, 9])


In [14]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = x*y
print(z)

tensor([ 4, 10, 18])


In [15]:
import torch

x = torch.tensor([3,5,7])
print(x.sum())

tensor(15)


In [16]:
import torch

x = torch.tensor([3.0, 6.0, 9.0])

print(x.mean())

tensor(6.)


In [17]:
import torch

x = torch.tensor([1, 2, 3]).to('cuda')
print(x)

tensor([1, 2, 3], device='cuda:0')


In [20]:
import torch

x = torch.tensor([5, 2, 3])
y = torch.square(x)

print(y)

tensor([25,  4,  9])


In [23]:
import torch
import torch.nn as nn

X = torch.tensor([[1.0], [2.0], [3.0]])
Y = torch.tensor([[3.0], [6.0], [9.0]])

model = nn.Linear(1,1)

loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for i in range(50):
    y_pred = model(X)
    loss = loss_fn(y_pred, Y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

test = torch.tensor([[10.0]])
print("Prediction:", model(test).item())

Prediction: 29.13848876953125
